### ISSUE TITLE
Suppress startup messages

### ISSUE THREAD

**Issue by biodavidjm** [braverock/PerformanceAnalytics#111]
I maintain a Bioconductor R package that is using the great `PerformanceAnalytics` package. The problem is that when any user loads my package, I get the `PerformanceAnalytics` message:

```
Package PerformanceAnalytics (1.5.2) loaded.
Copyright (c) 2004-2018 Peter Carl and Brian G. Peterson, GPL-2 | GPL-3
https://github.com/braverock/PerformanceAnalytics
```
Would you mind to remove it? The R community does not consider this a good practice. Please, check the message that I got (sent to the developers mailing list) from the Bioconductor community when I asked how to suppress this message:

> On Tue, Feb 19, 2019 at 8:39 AM Martin Morgan <mtmorgan.bioc@gmail.com> wrote:
> I think the best / only way to do this is to convince the author that this type of self-promotion is not helpful in the long run --- if all maintainers did this then a typical R session would start with 10's of these, and each would have no impact.
> 
> Martin

**Comment by braverock** [comment]
No offense intended to Martin Morgan, as I greatly appreciate his contributions to the R ecosysytem, but many many packages use startup messages.

You can easily suppress this:

    suppressMessages(require(PerformanceAnalytics))

There is also `suppressPackageStartupMessages`

Also, shouldn't you be using `@importFrom` if you are using `rozygen` or `imports()` in `NAMESPACE`, or  ? 

If `PerformanceAnalytics` is in `Suggests` and you are using a conditional `require` or `library`, then the `suppressMessages()` syntax is probably best.  otherwise, if you are importing the namespace on package load, no messages should be sent.

**Comment by biodavidjm** [comment]
That's exactly what I am using: 

```
#' @importFrom PerformanceAnalytics chart.Correlation
```
that roxygen is writing in `NAMESPACE` as `importFrom(PerformanceAnalytics,chart.Correlation)`

And I have tried adding `PerformanceAnalytics` both as `Imports` and `Suggests` and it doesn't matter: when loading my package `library(artMS)` it will display your message, which (I agree with Martin) is not nice.

I know that the user could use `suppressPackageStartupMessages(library(artMS))` but that is not the point: the point is that loading `library(artMS)` is showing your messages (my package -or any other package that I am importing- does not display any startup message). And based on Martin's response, it does not seem to be a way to suppress those messages within a package (I hope this changes one day)
