### ISSUE TITLE
Return.portfolio(geometric= TRUE) is an approximation?

### ISSUE THREAD

**Issue by red-swan** [braverock/PerformanceAnalytics#113]
This is more of a design question than anything. `Return.portfolio.arithmetic` returns back the accurate portfolio returns while `Return.portfolio.geometric` only approximates it. Why doesn't the `geometric` function just translate the log returns back to arithmetic, do the rebalancing (etc.) and translate everything back to log space?

Thank you kindly.

**Comment by braverock** [comment]
Have you read the [portfolio returns vignette](https://github.com/braverock/PerformanceAnalytics/blob/master/vignettes/portfolio_returns.pdf)?

It goes through all the calculations, and why they work the way they do.

Geometrically chained returns are always an approximation, so I'm not sure exactly what you are proposing, or what you are getting at?

Any time you are working in return space, rather than cash space, you are making certain assumptions, choosing a (changing) numerator and denominator, and applying the calculation at discrete points.  It isn't nearly as simple as people seem to think with adding up log returns, especially in a portfolio context.  Hopefully the vignette clarifies things, or at least lets us sharpen your queries into something that can be answered precisely?

**Comment by braverock** [comment]
@red-swan did I answer your question?  May we close this issue?

**Comment by red-swan** [comment]
I'm looking at this now and wondering what I was thinking. I think I was confused and thought the geometric referred to the data instead of to the function. Yes. We should close this. Thank you.
