### ISSUE TITLE
table.Drawdowns "From" or "Peak" starts one month Later than it should

### ISSUE THREAD

**Issue by ededovic** [braverock/PerformanceAnalytics#117]
table.Drawdowns starts one month later than it really should. For example, the first start date of the first S&P 500 drawdown is reported to be 2007-11-30, but if you look at the time series, the peak was really on 2007-10-31. PerTrac reports 2007-10-31 in this case. The end dates are agree. Drawdown amout of -52.56% also agrees. Here is [PerTrac definition](http://www.riordan-consulting.com/files/ex-post-risk-statistical-definitions-and-formulas.pdf80112d05.pdf). It may be just a matter of convention, but I think the reporting of the table should be clarified, for example, "From" should be replaced with "Peak". 

> library(qunatmod)
> library(PerformanceAnalytics)
> getSymbols("^GSPC",src='yahoo', from=as.Date('1997-12-31'),to=as.Date('2019-03-31'))
> GSPCm = period.apply(GSPC, endpoints(GSPC, on = "months"), last)
> table.Drawdowns((ROC(GSPCm$GSPC.Close,n=1,type="discrete")))

From | Trough | To | Depth | Length | To Trough | Recovery
-- | -- | -- | -- | -- | -- | --
**11/30/2007** | 2/27/2009 | 3/28/2013 | **-0.5256** | 65 | 16 | 49
9/29/2000 | 9/30/2002 | 5/31/2007 | -0.4628 | 81 | 25 | 56
7/31/1998 | 8/31/1998 | 11/30/1998 | -0.1557 | 5 | 2 | 3
10/31/2018 | 12/31/2018 | <NA> | -0.1397 | 7 | 3 |  
6/30/2015 | 9/30/2015 | 7/29/2016 | -0.0889 | 14 | 4 | 10

> spx["2007-08/2007-12"]

  | GSPC.Close
-- | --
8/31/2007 | 1473.99
9/28/2007 | 1526.75
**10/31/2007** | **1549.38**
11/30/2007 | 1481.14
12/31/2007 | 1468.36

From PerTrac:

Drawdown | Length | Recovery | Peak | Valley
-- | -- | -- | -- | --
**-52.56%** | 16 | 49 | **10/31/2007** | 2/28/2009
-46.28% | 25 | 56 | 8/31/2000 | 9/30/2002
-15.57% | 2 | 3 | 6/30/1998 | 8/31/1998
-13.97% | 3 | 0 | 9/30/2018 | 12/31/2018

**Comment by braverock** [comment]
I am closing this ticket, because your interpretation is incorrect.  

to your point ...

If the peak was at 2007-10-31, then the first reported period in which there is a drawdown is, as shown in your example, 2007-11-30.  The series was *not* _in a drawdown_ on 2007-10-31, so reporting that the series was in a drawdown on 2007-10-31 would be incorrect.

Our definition of loss from the peak matches Pertrac's.

Note that your Pertrac example doesn't report the period of a new peak, though the time to recover also agrees. 

I also don't understand why anyone, even in the fund industry, is still using monthly data.  We use daily data series for returns, and demand them from all our outside investments, as do almost all asset managers and investors at this point.  The only monthly or quarterly series I see anymore are macro data.
