### ISSUE TITLE
chart.Correlation - grobs conversion and main title addition

### ISSUE THREAD

**Issue by gnmcsbnfrmtcsclb** [braverock/PerformanceAnalytics#126]
Hi,
Two questions:
1. How can I add a main title to chart.Correlation?
2. How can I convert chart.Correlation to grobs, so I can mix and match with other plots generated by ggplots?
Thanks!

**Comment by braverock** [comment]
There is (unfortunately?) no way this chart will ever be a grob.  It has too many components, all constructed by using `layout`.  It isn't constructed in a way which would ever be compatible with the architecture of ggplot2.

We are working to make many of the other PerformanceAnalytics functions return a ggplot object, but `chart.Correlation` is not on the list, because it isn't a reasonable thing to even try.

**Comment by gnmcsbnfrmtcsclb** [comment]
OK, thanks for letting us know.
